name: Example

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: |
          echo Sleep
          sleep 15
          echo Hello, world!
          echo Kaboom
          exit 1
